// THIS FILE IS AUTO GENERATED: DO NOT EDIT THIS FILE. INSTEAD EDIT the implementation plan or configuration sources.
import eslint from '@eslint/js';
import tseslint from 'typescript-eslint';
import stylistic from '@stylistic/eslint-plugin';

export default tseslint.config(
  eslint.configs.recommended,
  ...tseslint.configs.strictTypeChecked,
  ...tseslint.configs.stylisticTypeChecked,
  // Server and shared files use tsconfig.json (NodeNext)
  {
    files: ['src/server/**/*.ts', 'src/shared/**/*.ts', 'test/unit/server/**/*.ts', 'test/unit/shared/**/*.ts', 'test/integration/**/*.ts', 'test/helpers/**/*.ts', 'test/mocks/**/*.ts', 'test/setup.ts', 'test/global-setup.ts', 'test/test-isolation.ts', 'test/e2e/**/*.ts', 'scripts/**/*.ts'],
    languageOptions: {
      parserOptions: {
        project: './tsconfig.json',
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
  // Client files use tsconfig.client.json (bundler)
  {
    files: ['src/client/**/*.ts', 'src/client/**/*.tsx', 'test/unit/client/**/*.ts', 'test/unit/client/**/*.tsx', 'test/utils/**/*.ts', 'test/utils/**/*.tsx'],
    languageOptions: {
      parserOptions: {
        project: './tsconfig.client.json',
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
  {
    plugins: {
      '@stylistic': stylistic,
    },
    rules: {
      '@stylistic/indent': ['error', 2],
      '@stylistic/quotes': ['error', 'single', { avoidEscape: true }],
      '@stylistic/semi': ['error', 'always'],
      '@stylistic/comma-dangle': ['error', 'always-multiline'],
      '@stylistic/object-curly-spacing': ['error', 'always'],
      '@stylistic/array-bracket-spacing': ['error', 'never'],
      '@stylistic/arrow-parens': ['error', 'always'],
      '@stylistic/eol-last': ['error', 'always'],
      '@stylistic/no-trailing-spaces': 'error',
      '@stylistic/no-multiple-empty-lines': ['error', { max: 1, maxEOF: 0 }],
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      '@typescript-eslint/explicit-function-return-type': 'error',
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/strict-boolean-expressions': 'off',
    },
  },
  {
    ignores: [
      'node_modules/**',
      'dist/**',
      'coverage/**',
      '*.config.*',
      '.husky/**',
    ],
  },
);
