// THIS FILE IS AUTO GENERATED: DO NOT EDIT THIS FILE. INSTEAD EDIT the implementation plan or configuration sources.
import { defineConfig, devices } from '@playwright/test';

/**
 * Playwright configuration for AIForge E2E tests
 *
 * Test isolation is handled by fixtures.ts which creates a fresh server
 * and data directory for each test file.
 *
 * @see https://playwright.dev/docs/test-configuration
 */
export default defineConfig({
  testDir: './test/e2e',
  /* Run tests in files in parallel - each file gets its own isolated server */
  fullyParallel: true,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 2 : 0,
  /* Use single worker in CI to avoid race conditions with shared server names */
  workers: 1,
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: process.env.CI ? 'github' : 'html',
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Base URL to use in actions like `await page.goto('/')`. */
    /* In CI, use fixed port 9061 (frontend via webServer config) */
    /* Locally, defer to fixture which uses servherd dynamic ports */
    baseURL: process.env.CI ? 'http://localhost:9061' : (process.env.E2E_BASE_URL ?? 'http://localhost:9060'),

    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on-first-retry',

    /* Take screenshot on failure */
    screenshot: 'only-on-failure',
  },

  /* Configure projects for major browsers */
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],

  /* Server configuration for CI - uses Playwright's built-in webServer instead of servherd */
  /* This avoids pm2 daemon issues in CI environments */
  ...(process.env.CI ? {
    webServer: [
      {
        command: 'E2E_TEST=true AIFORGE_PORT=9060 AIFORGE_AUTH_GUID=e2e-test-guid AIFORGE_DATA_DIR=./tmp/e2e-data tsx src/server/index.ts',
        port: 9060,
        reuseExistingServer: false,
        timeout: 120000,
      },
      {
        command: 'AIFORGE_SERVER_PORT=9060 vite --port 9061 --host',
        port: 9061,
        reuseExistingServer: false,
        timeout: 120000,
      },
    ],
  } : {}),

  /* Global timeout for tests */
  timeout: 30000,

  /* Expect timeout */
  expect: {
    timeout: 10000,
  },
});
