// THIS FILE IS AUTO GENERATED: DO NOT EDIT THIS FILE. INSTEAD EDIT the implementation plan or configuration sources.
import { defineConfig } from 'vite';
import { resolve } from 'path';
import react from '@vitejs/plugin-react';
import { VitePWA } from 'vite-plugin-pwa';

export default defineConfig({
  plugins: [
    react(),
    VitePWA({
      registerType: 'autoUpdate',
      workbox: {
        // Only precache the app shell assets
        maximumFileSizeToCacheInBytes: 3 * 1024 * 1024, // 3MB - main bundle is ~2.4MB
        globPatterns: ['**/*.{js,css,html,ico,png,svg,woff,woff2}'],
        // All API and WebSocket requests go straight to network
        navigateFallback: 'index.html',
        runtimeCaching: [
          {
            urlPattern: /^\/api\//,
            handler: 'NetworkOnly',
          },
          {
            urlPattern: /^\/ws/,
            handler: 'NetworkOnly',
          },
        ],
      },
      manifest: {
        name: 'AIForge - Agentic IDE',
        short_name: 'AIForge',
        description: 'A web-based IDE for 100% agentic coding - manage AI agents through terminals, not files',
        theme_color: '#1a1b1e',
        background_color: '#1a1b1e',
        display: 'standalone',
        scope: '/',
        start_url: '/',
        icons: [
          {
            src: 'icon-192.png',
            sizes: '192x192',
            type: 'image/png',
          },
          {
            src: 'icon-512.png',
            sizes: '512x512',
            type: 'image/png',
          },
          {
            src: 'icon-512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable',
          },
        ],
      },
    }),
  ],
  root: '.',
  publicDir: 'public',
  build: {
    outDir: 'dist/client',
    emptyOutDir: true,
  },
  resolve: {
    alias: {
      '@shared': resolve(__dirname, 'src/shared'),
      '@client': resolve(__dirname, 'src/client'),
      '@server': resolve(__dirname, 'src/server'),
    },
  },
  server: {
    port: 9000 + Math.floor(Math.random() * 100),
    strictPort: false,
    allowedHosts: process.env.HOST ? [process.env.HOST] : true,
    proxy: {
      '/api': {
        target: `http://localhost:${process.env.AIFORGE_SERVER_PORT || 9050}`,
        changeOrigin: true,
        secure: false,
      },
      '/ws': {
        target: `ws://localhost:${process.env.AIFORGE_SERVER_PORT || 9050}`,
        ws: true,
        changeOrigin: true,
      },
    },
  },
});
