// THIS FILE IS AUTO GENERATED: DO NOT EDIT THIS FILE. INSTEAD EDIT the implementation plan or configuration sources.
import { defineConfig } from 'vite';
import { resolve } from 'path';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  root: '.',
  publicDir: 'public',
  build: {
    outDir: 'dist/client',
    emptyOutDir: true,
  },
  resolve: {
    alias: {
      '@shared': resolve(__dirname, 'src/shared'),
      '@client': resolve(__dirname, 'src/client'),
      '@server': resolve(__dirname, 'src/server'),
    },
  },
  server: {
    port: 9000 + Math.floor(Math.random() * 100),
    strictPort: false,
    allowedHosts: process.env.HOST ? [process.env.HOST] : true,
    proxy: {
      '/api': {
        target: `http://localhost:${process.env.AIFORGE_SERVER_PORT || 9050}`,
        changeOrigin: true,
        secure: false,
      },
      '/ws': {
        target: `ws://localhost:${process.env.AIFORGE_SERVER_PORT || 9050}`,
        ws: true,
        changeOrigin: true,
      },
    },
  },
});
