/**
 * THIS FILE IS AUTO GENERATED: DO NOT EDIT THIS FILE.
 * Mock PTY implementation for unit tests
 */
import { EventEmitter } from 'events';
import { vi } from 'vitest';
import type { IPty, IPtyForkOptions, IDisposable } from '@homebridge/node-pty-prebuilt-multiarch';

/**
 * Mock PTY that simulates node-pty behavior for testing
 */
export class MockPty extends EventEmitter implements IPty {
  readonly pid: number;
  cols: number;
  rows: number;
  readonly process: string;
  handleFlowControl = false;

  private _writeBuffer: string[] = [];
  private _killed = false;
  private _dataListeners: ((data: string) => void)[] = [];
  private _exitListeners: ((exitCode: number, signal?: number) => void)[] = [];

  constructor(
    public file = '/bin/bash',
    public args: string[] = [],
    public options: IPtyForkOptions = {},
  ) {
    super();
    this.pid = options.uid ?? Math.floor(Math.random() * 100000) + 1000;
    this.cols = options.cols ?? 80;
    this.rows = options.rows ?? 24;
    this.process = file;
  }

  /**
   * Event handler for data - implements IEvent<string> pattern
   */
  onData = (listener: (e: string) => void): IDisposable => {
    this._dataListeners.push(listener);
    return {
      dispose: (): void => {
        const idx = this._dataListeners.indexOf(listener);
        if (idx >= 0) this._dataListeners.splice(idx, 1);
      },
    };
  };

  /**
   * Event handler for exit - implements IEvent pattern
   */
  onExit = (listener: (e: { exitCode: number; signal?: number }) => void): IDisposable => {
    const wrappedListener = (exitCode: number, signal?: number): void => {
      listener(signal !== undefined ? { exitCode, signal } : { exitCode });
    };
    this._exitListeners.push(wrappedListener);
    return {
      dispose: (): void => {
        const idx = this._exitListeners.indexOf(wrappedListener);
        if (idx >= 0) this._exitListeners.splice(idx, 1);
      },
    };
  };

  /**
   * Deprecated on() method for backwards compatibility.
   * EventEmitter.on() is inherited and works with simulateData/simulateExit
   * which call this.emit() in addition to direct listener calls.
   */

  /**
   * Write data to the PTY
   */
  write = vi.fn((data: string): void => {
    if (this._killed) return;
    this._writeBuffer.push(data);
  });

  /**
   * Resize the PTY
   */
  resize = vi.fn((columns: number, rows: number): void => {
    if (this._killed) return;
    this.cols = columns;
    this.rows = rows;
  });

  /**
   * Kill the PTY process
   */
  kill = vi.fn((signal?: string): void => {
    if (this._killed) return;
    this._killed = true;
    // Emit exit event
    this.simulateExit(signal === 'SIGKILL' ? 137 : 0);
  });

  /**
   * Clear the PTY buffer (no-op in mock)
   */
  clear(): void {
    // No-op in mock
  }

  /**
   * Pause the PTY
   */
  pause(): void {
    // No-op in mock
  }

  /**
   * Resume the PTY
   */
  resume(): void {
    // No-op in mock
  }

  // Test helper methods

  /**
   * Get all data that was written to this PTY
   */
  getWriteBuffer(): string[] {
    return [...this._writeBuffer];
  }

  /**
   * Check if the PTY was killed
   */
  isKilled(): boolean {
    return this._killed;
  }

  /**
   * Simulate data coming from the PTY
   */
  simulateData(data: string): void {
    for (const listener of this._dataListeners) {
      listener(data);
    }
    this.emit('data', data);
  }

  /**
   * Simulate the PTY process exiting
   */
  simulateExit(exitCode: number, signal?: number): void {
    this._killed = true;
    for (const listener of this._exitListeners) {
      listener(exitCode, signal);
    }
    this.emit('exit', { exitCode, signal });
  }
}

/**
 * Create a mock PTY instance
 */
export function createMockPty(options: Partial<IPtyForkOptions> = {}): MockPty {
  return new MockPty('/bin/bash', [], {
    cols: 80,
    rows: 24,
    cwd: '/tmp',
    ...options,
  });
}

/**
 * Create a mock PTY factory for use with PtyManager
 */
export function createMockPtyFactory(): (file: string, args: string[], options: IPtyForkOptions) => MockPty {
  return (file: string, args: string[], options: IPtyForkOptions) => {
    return new MockPty(file, args, options);
  };
}

/**
 * Type for the factory function
 */
export type PtyFactory = (file: string, args: string[], options: IPtyForkOptions) => IPty;
