/**
 * THIS FILE IS AUTO GENERATED: DO NOT EDIT THIS FILE.
 * Mock WebSocket implementation for unit tests
 */
import { EventEmitter } from 'events';
import { vi } from 'vitest';

/**
 * WebSocket ready states
 */
export const WebSocketReadyState = {
  CONNECTING: 0,
  OPEN: 1,
  CLOSING: 2,
  CLOSED: 3,
} as const;

/**
 * Mock WebSocket for testing server-side WebSocket handlers
 */
export class MockWebSocket extends EventEmitter {
  readyState: number = WebSocketReadyState.OPEN;
  isAlive = true;

  private _sent: unknown[] = [];
  private _closed = false;
  private _terminated = false;

  /**
   * Send data through the WebSocket
   */
  send = vi.fn((data: string | Buffer): void => {
    if (this._closed || this._terminated) return;

    let parsed: unknown;
    if (typeof data === 'string') {
      try {
        parsed = JSON.parse(data);
      } catch {
        parsed = data;
      }
    } else {
      parsed = data;
    }
    this._sent.push(parsed);
  });

  /**
   * Send a ping frame
   */
  ping = vi.fn((): void => {
    if (this._closed || this._terminated) return;
    // In real WebSocket, this would send a ping frame
  });

  /**
   * Send a pong frame
   */
  pong = vi.fn((): void => {
    if (this._closed || this._terminated) return;
    // In real WebSocket, this would send a pong frame
  });

  /**
   * Close the WebSocket connection
   */
  close = vi.fn((code?: number, reason?: string): void => {
    if (this._closed) return;
    this._closed = true;
    this.readyState = WebSocketReadyState.CLOSED;
    this.emit('close', code ?? 1000, reason ?? '');
  });

  /**
   * Terminate the WebSocket connection immediately
   */
  terminate = vi.fn((): void => {
    if (this._terminated) return;
    this._terminated = true;
    this._closed = true;
    this.readyState = WebSocketReadyState.CLOSED;
    this.emit('close', 1006, 'Connection terminated');
  });

  // Test helper methods

  /**
   * Get all messages that were sent through this WebSocket
   */
  get sent(): unknown[] {
    return [...this._sent];
  }

  /**
   * Clear the sent messages buffer
   */
  clearSent(): void {
    this._sent = [];
  }

  /**
   * Check if the WebSocket was closed
   */
  isClosed(): boolean {
    return this._closed;
  }

  /**
   * Check if the WebSocket was terminated
   */
  isTerminated(): boolean {
    return this._terminated;
  }

  /**
   * Simulate receiving a message from the client
   */
  simulateMessage(data: unknown): void {
    const message = typeof data === 'string' ? data : JSON.stringify(data);
    this.emit('message', message);
  }

  /**
   * Simulate a pong response from the client
   */
  simulatePong(): void {
    this.isAlive = true;
    this.emit('pong');
  }

  /**
   * Simulate the connection closing
   */
  simulateClose(code = 1000, reason = ''): void {
    this._closed = true;
    this.readyState = WebSocketReadyState.CLOSED;
    this.emit('close', code, reason);
  }

  /**
   * Simulate a connection error
   */
  simulateError(error: Error): void {
    this.emit('error', error);
  }

  /**
   * Simulate the connection opening
   */
  simulateOpen(): void {
    this.readyState = WebSocketReadyState.OPEN;
    this.emit('open');
  }
}

/**
 * Create a mock WebSocket instance
 */
export function createMockWebSocket(): MockWebSocket {
  return new MockWebSocket();
}

/**
 * Mock WebSocket Server for testing
 */
export class MockWebSocketServer extends EventEmitter {
  clients = new Set<MockWebSocket>();
  private _closed = false;

  /**
   * Add a client to the server
   */
  addClient(client: MockWebSocket): void {
    this.clients.add(client);
    client.on('close', () => {
      this.clients.delete(client);
    });
  }

  /**
   * Simulate a new client connection
   */
  simulateConnection(client?: MockWebSocket): MockWebSocket {
    const ws = client ?? createMockWebSocket();
    this.addClient(ws);
    this.emit('connection', ws);
    return ws;
  }

  /**
   * Close the WebSocket server
   */
  close = vi.fn((callback?: () => void): void => {
    if (this._closed) return;
    this._closed = true;

    // Close all clients
    for (const client of this.clients) {
      client.close();
    }
    this.clients.clear();

    if (callback) callback();
    this.emit('close');
  });

  /**
   * Check if server is closed
   */
  isClosed(): boolean {
    return this._closed;
  }
}

/**
 * Create a mock WebSocket server
 */
export function createMockWebSocketServer(): MockWebSocketServer {
  return new MockWebSocketServer();
}

/**
 * Mock client-side WebSocket for testing client code
 */
export class MockClientWebSocket extends EventEmitter {
  url: string;
  readyState: number = WebSocketReadyState.CONNECTING;

  private _sent: unknown[] = [];
  private _closed = false;

  // Event handlers that can be set by client code
  onopen: ((event: Event) => void) | null = null;
  onclose: ((event: CloseEvent) => void) | null = null;
  onmessage: ((event: MessageEvent) => void) | null = null;
  onerror: ((event: Event) => void) | null = null;

  constructor(url: string) {
    super();
    this.url = url;
    // Don't auto-open - tests should manually control connection state
  }

  /**
   * Send data through the WebSocket
   */
  send(data: string): void {
    if (this._closed || this.readyState !== WebSocketReadyState.OPEN) return;

    let parsed: unknown;
    try {
      parsed = JSON.parse(data);
    } catch {
      parsed = data;
    }
    this._sent.push(parsed);
  }

  /**
   * Close the WebSocket connection
   */
  close(code?: number, reason?: string): void {
    if (this._closed) return;
    this._closed = true;
    this.readyState = WebSocketReadyState.CLOSED;

    const event = { code: code ?? 1000, reason: reason ?? '' } as CloseEvent;
    if (this.onclose) this.onclose(event);
    this.emit('close', event);
  }

  // Test helper methods

  /**
   * Get all messages that were sent
   */
  get sent(): unknown[] {
    return [...this._sent];
  }

  /**
   * Simulate the connection opening
   */
  simulateOpen(): void {
    this.readyState = WebSocketReadyState.OPEN;
    const event = {} as Event;
    if (this.onopen) this.onopen(event);
    this.emit('open', event);
  }

  /**
   * Simulate receiving a message
   */
  simulateMessage(data: unknown): void {
    const message = typeof data === 'string' ? data : JSON.stringify(data);
    const event = { data: message } as MessageEvent;
    if (this.onmessage) this.onmessage(event);
    this.emit('message', event);
  }

  /**
   * Simulate the connection closing
   * @param code - Close code. Default 1006 (abnormal closure) to trigger reconnection
   */
  simulateClose(code = 1006, reason = ''): void {
    this._closed = true;
    this.readyState = WebSocketReadyState.CLOSED;

    const event = { code, reason } as CloseEvent;
    if (this.onclose) this.onclose(event);
    this.emit('close', event);
  }

  /**
   * Simulate an error
   */
  simulateError(error?: Error): void {
    const event = { error } as unknown as Event;
    if (this.onerror) this.onerror(event);
    this.emit('error', event);
  }
}

/**
 * Create a mock client WebSocket constructor for testing
 */
export function createMockWebSocketConstructor(): typeof MockClientWebSocket & {
  instances: MockClientWebSocket[];
  CONNECTING: number;
  OPEN: number;
  CLOSING: number;
  CLOSED: number;
} {
  const instances: MockClientWebSocket[] = [];

  const MockWebSocketClass = class extends MockClientWebSocket {
    constructor(url: string) {
      super(url);
      instances.push(this);
    }
  };

  return Object.assign(MockWebSocketClass, {
    instances,
    CONNECTING: WebSocketReadyState.CONNECTING,
    OPEN: WebSocketReadyState.OPEN,
    CLOSING: WebSocketReadyState.CLOSING,
    CLOSED: WebSocketReadyState.CLOSED,
  });
}
