#!/usr/bin/env npx tsx
/**
 * THIS FILE IS AUTO GENERATED: DO NOT EDIT THIS FILE
 * This script generates a random GUID for AIForge authentication
 */
import { randomUUID } from 'node:crypto';

const guid = randomUUID();

console.log('Generated authentication GUID:');
console.log('');
console.log(`  ${guid}`);
console.log('');
console.log('To use this GUID, either:');
console.log('');
console.log('1. Set the environment variable:');
console.log(`   export AIFORGE_AUTH_GUID="${guid}"`);
console.log('');
console.log('2. Or add to ~/.aiforge/config.json:');
console.log(`   { "authGuid": "${guid}" }`);
console.log('');
