/**
 * THIS FILE IS AUTO GENERATED: DO NOT EDIT THIS FILE.
 * WebSocket test utilities
 */
import WebSocket from 'ws';

/**
 * Options for connecting to a test WebSocket server
 */
export interface ConnectOptions {
  noAuth?: boolean;
  cookie?: string;
  timeout?: number;
}

/**
 * Wait for a WebSocket message matching criteria
 */
export async function waitForMessage<T = unknown>(
  ws: WebSocket,
  criteria: { type?: string; shellId?: string; contains?: string },
  timeout = 5000,
): Promise<T> {
  return new Promise((resolve, reject) => {
    const timeoutId = setTimeout(() => {
      ws.removeListener('message', messageHandler);
      reject(new Error(`Timeout waiting for message matching ${JSON.stringify(criteria)}`));
    }, timeout);

    function messageHandler(data: WebSocket.RawData): void {
      try {
        const message = JSON.parse(Buffer.from(data as Buffer).toString('utf8')) as Record<string, unknown>;

        let matches = true;
        if (criteria.type && message.type !== criteria.type) matches = false;
        if (criteria.shellId && message.shellId !== criteria.shellId) matches = false;
        if (criteria.contains && typeof message.data === 'string' && !message.data.includes(criteria.contains)) matches = false;

        if (matches) {
          clearTimeout(timeoutId);
          ws.removeListener('message', messageHandler);
          resolve(message as T);
        }
      } catch {
        // Ignore parse errors, keep waiting
      }
    }

    ws.on('message', messageHandler);
  });
}

/**
 * Send a message through a WebSocket
 */
export function sendMessage(ws: WebSocket, message: unknown): void {
  ws.send(JSON.stringify(message));
}

/**
 * Wait for a condition to be true
 */
export async function waitFor(
  condition: () => boolean | Promise<boolean>,
  options: { timeout?: number; interval?: number } = {},
): Promise<void> {
  const { timeout = 5000, interval = 50 } = options;
  const startTime = Date.now();

  while (Date.now() - startTime < timeout) {
    if (await condition()) {
      return;
    }
    await new Promise((resolve) => setTimeout(resolve, interval));
  }

  throw new Error(`Timeout waiting for condition after ${String(timeout)}ms`);
}

/**
 * Create a deferred promise for testing async flows
 */
export function createDeferred<T>(): {
  promise: Promise<T>;
  resolve: (value: T) => void;
  reject: (reason?: unknown) => void;
} {
  let resolve!: (value: T) => void;
  let reject!: (reason?: unknown) => void;

  const promise = new Promise<T>((res, rej) => {
    resolve = res;
    reject = rej;
  });

  return { promise, resolve, reject };
}

/**
 * Collect messages from a WebSocket until a condition is met
 */
export async function collectMessages<T = unknown>(
  ws: WebSocket,
  count: number,
  timeout = 5000,
): Promise<T[]> {
  const messages: T[] = [];

  return new Promise((resolve, reject) => {
    const timeoutId = setTimeout(() => {
      ws.removeListener('message', messageHandler);
      reject(new Error(`Timeout collecting ${String(count)} messages, got ${String(messages.length)}`));
    }, timeout);

    function messageHandler(data: WebSocket.RawData): void {
      try {
        const message = JSON.parse(Buffer.from(data as Buffer).toString('utf8')) as T;
        messages.push(message);

        if (messages.length >= count) {
          clearTimeout(timeoutId);
          ws.removeListener('message', messageHandler);
          resolve(messages);
        }
      } catch {
        // Ignore parse errors
      }
    }

    ws.on('message', messageHandler);
  });
}

/**
 * Wait for WebSocket to reach a ready state
 */
export async function waitForReadyState(
  ws: WebSocket,
  state: number,
  timeout = 5000,
): Promise<void> {
  if (ws.readyState === state) return;

  return new Promise((resolve, reject) => {
    const timeoutId = setTimeout(() => {
      reject(new Error(`Timeout waiting for ready state ${String(state)}`));
    }, timeout);

    const checkState = (): void => {
      if (ws.readyState === state) {
        clearTimeout(timeoutId);
        resolve();
      }
    };

    ws.on('open', checkState);
    ws.on('close', checkState);
    ws.on('error', checkState);
  });
}
